feat: add ci-attr flag. It permits to save ci context env as metadata
codenotary/vcn pull request #139
Opened 2021-04-08 16:56 UTC by mmeloni

2021-04-12 06:34 UTC, dmacvicar requested changes

2021-04-12 06:34 UTC, dmacvicar commented on pkg/cicontext/ci_context_saver.go
> +func GetCIContextMetadata() map[string]interface{} {
I'd use `os.LookupEnv` here to avoid doing the split yourself.

Eg. iterate over the whitelist, and then use os.LookupEnv to check if it is there and get the value at the same time.

2021-04-12 06:34 UTC, dmacvicar commented on pkg/cicontext/whitelist.go
> +	"CI": 1,
Why are you using an int here?

2021-04-12 06:34 UTC, dmacvicar commented on pkg/cicontext/whitelist.go
> +	"CI": 1,
I think it would be useful to store the detected CI. eg. VCN_CI_ENV=gitlab. or something like that.

2021-04-12 13:25 UTC, mmeloni commented on pkg/cicontext/whitelist.go
> +	"CI": 1,
The reason is to use a map, but if we loop through the whitelist I could also use an array of string

2021-04-12 13:27 UTC, mmeloni commented on pkg/cicontext/whitelist.go
> +	"CI": 1,
To determine the CI I could look at gitlab prefix (CI), github (GITHUB) and for jenkins that has not a prefix I could look for JENKINS_HOME or JENKINS_URL

2021-04-12 13:28 UTC, mmeloni commented on pkg/cicontext/ci_context_saver.go
> +func GetCIContextMetadata() map[string]interface{} {
ok

2021-04-13 10:55 UTC, dmacvicar commented
How is this tested?

2021-04-13 12:22 UTC, mmeloni commented
I tested it only on github. If it works I could also test it on gitlab. Help is needed for Jenkins

2021-04-14 05:57 UTC, dmacvicar approved these changes

2021-04-14 05:57 UTC, merged